### ISSUE TITLE
Home - Product

### ISSUE THREAD

**Issue by ibndawood** [Transvelo/reen#1]
http://demo.fuviz.com/reen/v2-1/index.html

- [x] Main Slider with Captions - https://github.com/Transvelo/reen-gutenberg-blocks/issues/1 - @akther80 
- [x] Product - https://github.com/Transvelo/reen-gutenberg-blocks/issues/8 - @nilofer-farzana 
- [x] Call to Action 1 - http://demo.fuviz.com/reen/v2-1/index.html- @yousufansa 
- [x] Circle Tabs - https://github.com/Transvelo/reen-gutenberg-blocks/issues/3- @nilofer-farzana 
- [x] Call to Action 2 - http://demo.fuviz.com/reen/v2-1/index.html - @yousufansa 

https://demo2.madrasthemes.com/reen/
