### ISSUE TITLE
Home - One Page - Agency

### ISSUE THREAD

**Issue by ibndawood** [Transvelo/reen#18]
http://demo.fuviz.com/reen/v2-1/one-page3.html

- [x] Main Slider with Captions - https://github.com/Transvelo/reen-gutenberg-blocks/issues/1 - @akther80 
- [x] Icon Control - https://github.com/Transvelo/reen-gutenberg-blocks/issues/6 - @aslamahamed13 
- [x] Portfolio Block - https://github.com/Transvelo/reen-gutenberg-blocks/issues/11 - @nilofer-farzana 
- [x] Portfolio Carousel - https://github.com/Transvelo/reen-gutenberg-blocks/issues/1 - @akther80 
- [x] Call to Action 2 - http://demo.fuviz.com/reen/v2-1/index.html - @yousufansa 

https://demo2.madrasthemes.com/reen/agency-style/
