### ISSUE TITLE
Home - One Page - Portfolio

### ISSUE THREAD

**Issue by ibndawood** [Transvelo/reen#19]
http://demo.fuviz.com/reen/v2-1/one-page4.html

- [x] Portfolio Carousel - https://github.com/Transvelo/reen-gutenberg-blocks/issues/1 - @akther80 
- [x] Portfolio Block - https://github.com/Transvelo/reen-gutenberg-blocks/issues/11 - @nilofer-farzana 
- [x] Clients Carousel - https://github.com/Transvelo/reen-gutenberg-blocks/issues/1 - @akther80 

https://demo2.madrasthemes.com/reen/portfolio-style/
