### ISSUE TITLE
Home - Service

### ISSUE THREAD

**Issue by ibndawood** [Transvelo/reen#2]
http://demo.fuviz.com/reen/v2-1/index2.html

- [x] Main Slider with Captions - https://github.com/Transvelo/reen-gutenberg-blocks/issues/1 - @akther80 
- [x] Features
- [x] 2 Big Tabs - https://github.com/Transvelo/reen-gutenberg-blocks/issues/3- @nilofer-farzana 
- [x] Icon Control - https://github.com/Transvelo/reen-gutenberg-blocks/issues/6 - @aslamahamed13 
- [x] Testimonials Carousel 
- [x] Call to Action 2 - http://demo.fuviz.com/reen/v2-1/index.html - @yousufansa 

https://demo2.madrasthemes.com/reen/service-style/
