### ISSUE TITLE
Pages - About Creative

### ISSUE THREAD

**Issue by ibndawood** [Transvelo/reen#6]
http://demo.fuviz.com/reen/v2-1/about.html

- [x] Section Block - https://github.com/Transvelo/reen-gutenberg-blocks/issues/7- @aslamahamed13 
- [x] Columns Block - https://github.com/Transvelo/reen-gutenberg-blocks/issues/8- @nilofer-farzana 
- [x] Team Member- https://github.com/Transvelo/reen-gutenberg-blocks/issues/13 - @abubacker7 
- [x] Icon Block- https://github.com/Transvelo/reen-gutenberg-blocks/issues/6 - @aslamahamed13 
- [x] Client Carousel- https://github.com/Transvelo/reen-gutenberg-blocks/issues/1 - @akther80 
- [x] Call to Action- https://github.com/Transvelo/reen-gutenberg-blocks/issues/9 - @yousufansa 

https://demo2.madrasthemes.com/reen/about-1/
