### ISSUE TITLE
Pages - About Agency

### ISSUE THREAD

**Issue by ibndawood** [Transvelo/reen#7]
http://demo.fuviz.com/reen/v2-1/about2.html

- [x] Columns Block - https://github.com/Transvelo/reen-gutenberg-blocks/issues/8- @nilofer-farzana 
- [x] Icon Block- https://github.com/Transvelo/reen-gutenberg-blocks/issues/6 - @aslamahamed13 
- [x] Hero Carousel- https://github.com/Transvelo/reen-gutenberg-blocks/issues/1 - @akther80 
- [x] Section Block - https://github.com/Transvelo/reen-gutenberg-blocks/issues/7- @aslamahamed13 
- [x] Call to Action- https://github.com/Transvelo/reen-gutenberg-blocks/issues/9 - @yousufansa 

https://demo2.madrasthemes.com/reen/about-2/
