### ISSUE TITLE
Pages - Services I

### ISSUE THREAD

**Issue by ibndawood** [Transvelo/reen#8]
http://demo.fuviz.com/reen/v2-1/services.html

- [x] Section - https://github.com/Transvelo/reen-gutenberg-blocks/issues/7 - @aslamahamed13 
- [x] Tabs - https://github.com/Transvelo/reen-gutenberg-blocks/issues/3 - @nilofer-farzana 
- [x] Accordion, Video Player - https://github.com/Transvelo/reen-gutenberg-blocks/issues/4 - @abubacker7 
- [x] Clients Carousel - https://github.com/Transvelo/reen-gutenberg-blocks/issues/1 - @akther80 
- [x] Call to Action - https://github.com/Transvelo/reen-gutenberg-blocks/issues/9 - @yousufansa

https://demo2.madrasthemes.com/reen/services-1/
