### ISSUE TITLE
Pages - Services II

### ISSUE THREAD

**Issue by ibndawood** [Transvelo/reen#9]
http://demo.fuviz.com/reen/v2-1/services2.html

- [x] Icon Block - https://github.com/Transvelo/reen-gutenberg-blocks/issues/15 - @aslamahamed13 
- [x] Post Carousel - https://github.com/Transvelo/reen-gutenberg-blocks/issues/1 - @akther80 
- [x] Clients Carousel - https://github.com/Transvelo/reen-gutenberg-blocks/issues/1 - @akther80 
- [x] Call to Action - https://github.com/Transvelo/reen-gutenberg-blocks/issues/9 - @yousufansa

https://demo2.madrasthemes.com/reen/services-2/
